# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.CharField(max_length=1000)),
                ('project_date', models.DateTimeField(verbose_name='Project Date')),
                ('project_githubLink', models.CharField(max_length=200)),
            ],
        ),
    ]
